#!/bin/bash
exec </dev/null >/tmp/hook_commit.log 2>&1
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$(dirname "$SCRIPT_DIR")/code"
bundle exec rubocop || exit 1
bundle exec rspec || exit 1
exit 0
