apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dude
  tags:
    - pillar-pro-people
    - valuestream-talent-acquisition
    - subvaluestream-recruiting
  description: this is the dude's metaverse
  annotations:
    github.com/project-slug: UKGEPIC/dude
    trove/enabled: "false"
spec:
  type: doc
  lifecycle: production
  system: library
  owner: user:default/maykel-suarez_ukg
