AllCops:
  TargetRubyVersion: 3.0
  NewCops: disable
  SuggestExtensions: false

# The ones we care about
Metrics/MethodLength:
  Max: 5

Metrics/ClassLength:
  Max: 100

Metrics/ModuleLength:
  Max: 100

# Disable everything else
Layout:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Lint:
  Enabled: false

Naming:
  Enabled: false

Naming/FileName:
  Enabled: true
  ExpectMatchingDefinition: true
  CheckDefinitionPathHierarchy: true
  CheckDefinitionPathHierarchyRoots:
    - lib

Style:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested

Bundler:
  Enabled: false

Gemspec:
  Enabled: false

Security:
  Enabled: false
