name: coolban

on:
  issues:
    types: [labeled]
  workflow_dispatch:
    inputs:
      prompt:
        type: string
        description: "skill to run (e.g. /3-amigos)"
        required: true
      issue:
        type: number
        description: "issue number"
        required: false
      timeout:
        type: number
        description: "timeout in minutes"
        required: false

jobs:
  coolban:
    if: >-
      inputs.prompt ||
      contains(fromJSON('["🪇 amigos","🥒 gherkin","🏔️ katmandu"]'), github.event.label.name)
    uses: ./.github/workflows/claude.yml
    with:
      trigger_phrase: "@dude"
      prompt: >-
        ${{ inputs.prompt ||
            (github.event.label.name == '🪇 amigos' && '/3-amigos') ||
            (github.event.label.name == '🥒 gherkin' && '/gherkin') ||
            (github.event.label.name == '🏔️ katmandu' && '/katmandu') }}
        #${{ github.event.issue.number || inputs.issue || '' }}
      reaction: "rocket"
      timeout: ${{ inputs.timeout && fromJSON(inputs.timeout) || 30 }}
    secrets:
      LITELLM_KEY: ${{ secrets.LITELLM_KEY }}
