name: dude

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  issues:
    types: [opened, labeled]
  workflow_dispatch:
    inputs:
      prompt:
        type: string
        description: "@dude"
        required: true
      version:
        type: string
        description: "claude-code version"
        required: false
      timeout:
        type: number
        description: "timeout in minutes"
        required: false

jobs:
  dude:
    if: >-
      inputs.prompt ||
      contains(toJson(github.event), '@dude') ||
      contains(github.event.issue.labels.*.name, 'dude')
    uses: ./.github/workflows/claude.yml
    with:
      trigger_phrase: "@dude"
      prompt: ${{ inputs.prompt || '' }}
      version: ${{ inputs.version || '' }}
      timeout: ${{ inputs.timeout && fromJSON(inputs.timeout) || 30 }}
      reaction: "+1"
    secrets:
      LITELLM_KEY: ${{ secrets.LITELLM_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}
