name: dude

on:
  workflow_dispatch:
    inputs:
      prompt:
        type: string
        required: true
      version:
        type: string
        required: false
      cwd:
        type: string
        required: false
      timeout:
        type: number
        required: false
      claude_args:
        type: string
        required: false
permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write

jobs:
  dude:
    runs-on: garm-dev-dlas1-vm-linux-mega-large
    timeout-minutes: ${{ inputs.timeout || 30 }}
    env:
      GH_TOKEN: ${{ github.token }}
      ANTHROPIC_BASE_URL: https://sdlc-llm.ukg.int
      ANTHROPIC_AUTH_TOKEN: ${{ secrets.LITELLM_KEY }}
    steps:
      - name: Test
        run: echo "hello"
