name: loop

on:
  projects_v2_item:
    types: [edited]

jobs:
  set-loop:
    runs-on: ubuntu-latest
    if: ${{ github.event.changes.field_value.field_name == 'Status' && github.event.changes.field_value.to.name == 'DUDE-WIP' }}
    steps:
      - name: Set Loop to 3-amigos
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api graphql -f query='mutation { updateProjectV2ItemFieldValue(input: { projectId: "PVT_kwDOCAfaJ84BMtT6" itemId: "${{ github.event.projects_v2_item.node_id }}" fieldId: "PVTSSF_lADOCAfaJ84BMtT6zhBJfLE" value: { singleSelectOptionId: "3dbbdea4" } }) { projectV2Item { id } } }'
