name: test-dude

on:
  workflow_dispatch:
    inputs:
      prompt:
        type: string
        description: prompt
        required: true

jobs:
  test:
    uses: ./.github/workflows/dude.yml
    with:
      prompt: ${{ inputs.prompt }}
      claude_args: --dangerously-skip-permissions
    secrets:
      LITELLM_KEY: ${{ secrets.LITELLM_KEY }}
